# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: cutepig's blog
email: jinshouhe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  专注于计算机视觉，和C++
  CP程序员在香港。
  内容介绍：软件开发，软件工具的用法等视频教程
  youtube频道 https://www.youtube.com/channel/UCpAl4ajgAWBepDA1UjMC8CA
  blog http://cutepig.cnblogs.com/
  blog https://cutepig123.github.io/
  github https://github.com/cutepig123
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cutepig123.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NA
github_username:  cutepig123

permalink: /posts/:year-:month-:day-:title.html
#permalink: /:categories/:year/:month/:day/:title:output_ext
#exclude: [images]

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
